spring.application.name=internal-wallet
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/internal_wallet}
spring.datasource.username=${DB_USER:wallet_app}
spring.datasource.password=${DB_PASSWORD:}
spring.flyway.enabled=true
spring.jackson.deserialization.fail-on-unknown-properties=false
server.error.include-message=never
server.error.include-stacktrace=never
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=2MB
